
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'adv_dbt_ga4'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'adv_dbt_ga4'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  adv_dbt_ga4:
    staging:
      events:
        cta_click_custom_parameters:
          - name: click_text
            value_type: string_value
          - name: click_target
            value_type: string_value
        cta_view_custom_parameters:
          - name: cta_type
            value_type: string_value
        form_start_custom_parameters:
          - name: form_destination
            value_type: string_value 
          - name: form_length
            value_type: int_value
        form_submit_custom_parameters:
          - name: form_destination
            value_type: string_value
          - name: form_length
            value_type: int_value
          - name: form_id
            value_type: string_value
  ga4:
    source_project: "cj-data-warehouse-417316" # Project that contains raw GA4 data
    property_ids: [244396510] # Array of properties to process
    start_date: "{{ env_var ('DBT_GA4_START_DATE') }}" # Earliest date to load
    query_parameter_exclusions: ['msclkid', 'li_fat_id', 'token', 'hsa_net', 'hsa_cam', '_x_tr_hl', '_x_tr_pto', 'hsa_ver', 'x-craft-preview', '__hstc', 'hsa_ad', 'utm_term', 'hsa_acc', 'gclid', '__hsfp', 'gad_source', 'wbraid', 'gbraid', 'hsa_mt', 'hsa_tgt', 'utm_source', 'utm_medium', 'utm_content', 'nis', 'previewLLSession', 'li_giant', '_x_tr_sl', '_x_tr_tl', 'hsa_grp', 'utm_campaign', 'hsa_src', 'fbclid', '_hsenc', 'hsa_kw', 'trk', '_hsmi', '__hssc']
  static_incremental_days: 3 # Number of days to scan and reprocess on each run
  conversion_events: ['purchase']
  page_view_custom_parameters:
    - name: "category"
      value_type: "string_value"
    - name: "word_count"
      value_type: "int_value"
  
models:
  adv_dbt_ga4:
    marts:
      +schema: marts
    staging:
      +schema: stg
  ga4:
    marts:
      +schema: marts
    staging:
      +schema: stg
      recommended_events:
        stg_ga4__event_add_payment_info:
          +enabled: true
        stg_ga4__event_begin_checkout:
          +enabled: true
        stg_ga4__event_purchase:
          +enabled: true 
        stg_ga4__event_view_item:
          +enabled: true
    seeds:
      +schema: seed
